INSERT INTO TB_LEAGUE (NAME) VALUES ('Brasileirão');
INSERT INTO TB_LEAGUE (NAME) VALUES ('Premier League');
INSERT INTO TB_LEAGUE (NAME) VALUES ('La Liga');
INSERT INTO TB_LEAGUE (NAME) VALUES ('Serie A');
INSERT INTO TB_LEAGUE (NAME) VALUES ('Bundesliga');
INSERT INTO TB_LEAGUE (NAME) VALUES ('Ligue 1');
INSERT INTO TB_LEAGUE (NAME) VALUES ('Primeira Liga');