INSERT INTO TB_COMPETITION (NAME, CREATED_AT) VALUES ('Brasileirão', NOW());
INSERT INTO TB_COMPETITION (NAME, CREATED_AT) VALUES ('Premier League', NOW());
INSERT INTO TB_COMPETITION (NAME, CREATED_AT) VALUES ('La Liga', NOW());
INSERT INTO TB_COMPETITION (NAME, CREATED_AT) VALUES ('Serie A', NOW());
INSERT INTO TB_COMPETITION (NAME, CREATED_AT) VALUES ('Bundesliga', NOW());
INSERT INTO TB_COMPETITION (NAME, CREATED_AT) VALUES ('Ligue 1', NOW());
INSERT INTO TB_COMPETITION (NAME, CREATED_AT) VALUES ('Primeira Liga', NOW());
INSERT INTO TB_COMPETITION (NAME, CREATED_AT) VALUES ('Champions League', NOW());

-- Inserir clubes do Brasileirão
INSERT INTO TB_CLUB (NAME) VALUES ('Flamengo');
INSERT INTO TB_CLUB (NAME) VALUES ('Palmeiras');
INSERT INTO TB_CLUB (NAME) VALUES ('São Paulo');
INSERT INTO TB_CLUB (NAME) VALUES ('Corinthians');
INSERT INTO TB_CLUB (NAME) VALUES ('Atlético Mineiro');
INSERT INTO TB_CLUB (NAME) VALUES ('Grêmio');
INSERT INTO TB_CLUB (NAME) VALUES ('Fluminense');
INSERT INTO TB_CLUB (NAME) VALUES ('Internacional');
INSERT INTO TB_CLUB (NAME) VALUES ('Cruzeiro');
INSERT INTO TB_CLUB (NAME) VALUES ('Botafogo');
INSERT INTO TB_CLUB (NAME) VALUES ('Santos');
INSERT INTO TB_CLUB (NAME) VALUES ('Athletico Paranaense');
INSERT INTO TB_CLUB (NAME) VALUES ('Bahia');
INSERT INTO TB_CLUB (NAME) VALUES ('Vasco da Gama');
INSERT INTO TB_CLUB (NAME) VALUES ('Fortaleza');
INSERT INTO TB_CLUB (NAME) VALUES ('Ceará');
INSERT INTO TB_CLUB (NAME) VALUES ('Goiás');
INSERT INTO TB_CLUB (NAME) VALUES ('Red Bull Bragantino');
INSERT INTO TB_CLUB (NAME) VALUES ('América Mineiro');
INSERT INTO TB_CLUB (NAME) VALUES ('Coritiba');

-- Inserir clubes da Premier League
INSERT INTO TB_CLUB (NAME) VALUES ('Manchester United');
INSERT INTO TB_CLUB (NAME) VALUES ('Manchester City');
INSERT INTO TB_CLUB (NAME) VALUES ('Chelsea');
INSERT INTO TB_CLUB (NAME) VALUES ('Arsenal');
INSERT INTO TB_CLUB (NAME) VALUES ('Liverpool');
INSERT INTO TB_CLUB (NAME) VALUES ('Tottenham Hotspur');
INSERT INTO TB_CLUB (NAME) VALUES ('Everton');
INSERT INTO TB_CLUB (NAME) VALUES ('Leicester City');
INSERT INTO TB_CLUB (NAME) VALUES ('West Ham United');
INSERT INTO TB_CLUB (NAME) VALUES ('Aston Villa');
INSERT INTO TB_CLUB (NAME) VALUES ('Wolverhampton Wanderers');
INSERT INTO TB_CLUB (NAME) VALUES ('Newcastle United');
INSERT INTO TB_CLUB (NAME) VALUES ('Brighton & Hove Albion');
INSERT INTO TB_CLUB (NAME) VALUES ('Leeds United');
INSERT INTO TB_CLUB (NAME) VALUES ('Brentford');
INSERT INTO TB_CLUB (NAME) VALUES ('Crystal Palace');
INSERT INTO TB_CLUB (NAME) VALUES ('Fulham');
INSERT INTO TB_CLUB (NAME) VALUES ('Sheffield United');
INSERT INTO TB_CLUB (NAME) VALUES ('Burnley');
INSERT INTO TB_CLUB (NAME) VALUES ('Luton Town');

-- Inserir clubes da La Liga
INSERT INTO TB_CLUB (NAME) VALUES ('Real Madrid');
INSERT INTO TB_CLUB (NAME) VALUES ('Barcelona');
INSERT INTO TB_CLUB (NAME) VALUES ('Atletico Madrid');
INSERT INTO TB_CLUB (NAME) VALUES ('Sevilla');
INSERT INTO TB_CLUB (NAME) VALUES ('Valencia');
INSERT INTO TB_CLUB (NAME) VALUES ('Real Betis');
INSERT INTO TB_CLUB (NAME) VALUES ('Real Sociedad');
INSERT INTO TB_CLUB (NAME) VALUES ('Villarreal');
INSERT INTO TB_CLUB (NAME) VALUES ('Athletic Bilbao');
INSERT INTO TB_CLUB (NAME) VALUES ('Celta Vigo');
INSERT INTO TB_CLUB (NAME) VALUES ('Espanyol');
INSERT INTO TB_CLUB (NAME) VALUES ('Getafe');
INSERT INTO TB_CLUB (NAME) VALUES ('Mallorca');
INSERT INTO TB_CLUB (NAME) VALUES ('Osasuna');
INSERT INTO TB_CLUB (NAME) VALUES ('Rayo Vallecano');
INSERT INTO TB_CLUB (NAME) VALUES ('Granada');
INSERT INTO TB_CLUB (NAME) VALUES ('Alavés');
INSERT INTO TB_CLUB (NAME) VALUES ('Cádiz');
INSERT INTO TB_CLUB (NAME) VALUES ('Girona');
INSERT INTO TB_CLUB (NAME) VALUES ('Almería');

-- Inserir clubes da Serie A (Itália)
INSERT INTO TB_CLUB (NAME) VALUES ('Juventus');
INSERT INTO TB_CLUB (NAME) VALUES ('AC Milan');
INSERT INTO TB_CLUB (NAME) VALUES ('Inter Milan');
INSERT INTO TB_CLUB (NAME) VALUES ('AS Roma');
INSERT INTO TB_CLUB (NAME) VALUES ('Napoli');
INSERT INTO TB_CLUB (NAME) VALUES ('Lazio');
INSERT INTO TB_CLUB (NAME) VALUES ('Atalanta');
INSERT INTO TB_CLUB (NAME) VALUES ('Fiorentina');
INSERT INTO TB_CLUB (NAME) VALUES ('Torino');
INSERT INTO TB_CLUB (NAME) VALUES ('Bologna');
INSERT INTO TB_CLUB (NAME) VALUES ('Sassuolo');
INSERT INTO TB_CLUB (NAME) VALUES ('Udinese');
INSERT INTO TB_CLUB (NAME) VALUES ('Genoa');
INSERT INTO TB_CLUB (NAME) VALUES ('Cagliari');
INSERT INTO TB_CLUB (NAME) VALUES ('Salernitana');
INSERT INTO TB_CLUB (NAME) VALUES ('Empoli');
INSERT INTO TB_CLUB (NAME) VALUES ('Hellas Verona');
INSERT INTO TB_CLUB (NAME) VALUES ('Sampdoria');
INSERT INTO TB_CLUB (NAME) VALUES ('Spezia');
INSERT INTO TB_CLUB (NAME) VALUES ('Frosinone');

-- Inserir clubes da Bundesliga (Alemanha)
INSERT INTO TB_CLUB (NAME) VALUES ('Bayern Munich');
INSERT INTO TB_CLUB (NAME) VALUES ('Borussia Dortmund');
INSERT INTO TB_CLUB (NAME) VALUES ('RB Leipzig');
INSERT INTO TB_CLUB (NAME) VALUES ('Bayer Leverkusen');
INSERT INTO TB_CLUB (NAME) VALUES ('VfL Wolfsburg');
INSERT INTO TB_CLUB (NAME) VALUES ('Eintracht Frankfurt');
INSERT INTO TB_CLUB (NAME) VALUES ('Borussia Mönchengladbach');
INSERT INTO TB_CLUB (NAME) VALUES ('SC Freiburg');
INSERT INTO TB_CLUB (NAME) VALUES ('Union Berlin');
INSERT INTO TB_CLUB (NAME) VALUES ('VfB Stuttgart');
INSERT INTO TB_CLUB (NAME) VALUES ('FC Augsburg');
INSERT INTO TB_CLUB (NAME) VALUES ('Mainz 05');
INSERT INTO TB_CLUB (NAME) VALUES ('Hertha Berlin');
INSERT INTO TB_CLUB (NAME) VALUES ('Werder Bremen');
INSERT INTO TB_CLUB (NAME) VALUES ('Schalke 04');
INSERT INTO TB_CLUB (NAME) VALUES ('Hoffenheim');
INSERT INTO TB_CLUB (NAME) VALUES ('FC Köln');
INSERT INTO TB_CLUB (NAME) VALUES ('Fortuna Düsseldorf');

-- Inserir clubes da Ligue 1 (França)
INSERT INTO TB_CLUB (NAME) VALUES ('Paris Saint-Germain');
INSERT INTO TB_CLUB (NAME) VALUES ('Olympique Marseille');
INSERT INTO TB_CLUB (NAME) VALUES ('Lyon');
INSERT INTO TB_CLUB (NAME) VALUES ('Monaco');
INSERT INTO TB_CLUB (NAME) VALUES ('Lille');
INSERT INTO TB_CLUB (NAME) VALUES ('Rennes');
INSERT INTO TB_CLUB (NAME) VALUES ('Nice');
INSERT INTO TB_CLUB (NAME) VALUES ('Nantes');
INSERT INTO TB_CLUB (NAME) VALUES ('Strasbourg');
INSERT INTO TB_CLUB (NAME) VALUES ('Lens');
INSERT INTO TB_CLUB (NAME) VALUES ('Montpellier');
INSERT INTO TB_CLUB (NAME) VALUES ('Reims');
INSERT INTO TB_CLUB (NAME) VALUES ('Toulouse');
INSERT INTO TB_CLUB (NAME) VALUES ('Brest');
INSERT INTO TB_CLUB (NAME) VALUES ('Metz');
INSERT INTO TB_CLUB (NAME) VALUES ('Clermont Foot');
INSERT INTO TB_CLUB (NAME) VALUES ('Angers');
INSERT INTO TB_CLUB (NAME) VALUES ('Ajaccio');
INSERT INTO TB_CLUB (NAME) VALUES ('Auxerre');
INSERT INTO TB_CLUB (NAME) VALUES ('Lorient');

-- Inserir clubes da Primeira Liga (Portugal)
INSERT INTO TB_CLUB (NAME) VALUES ('Benfica');
INSERT INTO TB_CLUB (NAME) VALUES ('Porto');
INSERT INTO TB_CLUB (NAME) VALUES ('Sporting CP');
INSERT INTO TB_CLUB (NAME) VALUES ('Braga');
INSERT INTO TB_CLUB (NAME) VALUES ('Vitória de Guimarães');
INSERT INTO TB_CLUB (NAME) VALUES ('Boavista');
INSERT INTO TB_CLUB (NAME) VALUES ('Marítimo');
INSERT INTO TB_CLUB (NAME) VALUES ('Rio Ave');
INSERT INTO TB_CLUB (NAME) VALUES ('Famalicão');
INSERT INTO TB_CLUB (NAME) VALUES ('Paços de Ferreira');
INSERT INTO TB_CLUB (NAME) VALUES ('Santa Clara');
INSERT INTO TB_CLUB (NAME) VALUES ('Gil Vicente');
INSERT INTO TB_CLUB (NAME) VALUES ('Estoril');
INSERT INTO TB_CLUB (NAME) VALUES ('Arouca');
INSERT INTO TB_CLUB (NAME) VALUES ('Casa Pia');
INSERT INTO TB_CLUB (NAME) VALUES ('Chaves');
INSERT INTO TB_CLUB (NAME) VALUES ('Moreirense');
INSERT INTO TB_CLUB (NAME) VALUES ('Portimonense');
INSERT INTO TB_CLUB (NAME) VALUES ('Feirense');
INSERT INTO TB_CLUB (NAME) VALUES ('Tondela');

-- Inserir clubes do Brasileirão (COMPETITION_ID = 1)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (1, 1); -- Flamengo
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (2, 1); -- Palmeiras
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (3, 1); -- São Paulo
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (4, 1); -- Corinthians
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (5, 1); -- Atlético Mineiro
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (6, 1); -- Grêmio
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (7, 1); -- Fluminense
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (8, 1); -- Internacional
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (9, 1); -- Cruzeiro
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (10, 1); -- Botafogo
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (11, 1); -- Santos
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (12, 1); -- Athletico Paranaense
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (13, 1); -- Bahia
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (14, 1); -- Vasco da Gama
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (15, 1); -- Fortaleza
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (16, 1); -- Ceará
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (17, 1); -- Goiás
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (18, 1); -- Red Bull Bragantino
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (19, 1); -- América Mineiro
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (20, 1); -- Coritiba

-- Inserir clubes da Premier League (COMPETITION_ID = 2)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (21, 2); -- Manchester United
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (22, 2); -- Manchester City
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (23, 2); -- Chelsea
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (24, 2); -- Arsenal
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (25, 2); -- Liverpool
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (26, 2); -- Tottenham Hotspur
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (27, 2); -- Everton
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (28, 2); -- Leicester City
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (29, 2); -- West Ham United
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (30, 2); -- Aston Villa
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (31, 2); -- Wolverhampton Wanderers
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (32, 2); -- Newcastle United
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (33, 2); -- Brighton & Hove Albion
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (34, 2); -- Leeds United
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (35, 2); -- Brentford
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (36, 2); -- Crystal Palace
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (37, 2); -- Fulham
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (38, 2); -- Sheffield United
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (39, 2); -- Burnley
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (40, 2); -- Luton Town

-- Inserir clubes da La Liga (COMPETITION_ID = 3)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (41, 3); -- Real Madrid
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (42, 3); -- Barcelona
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (43, 3); -- Atletico Madrid
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (44, 3); -- Sevilla
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (45, 3); -- Valencia
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (46, 3); -- Real Betis
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (47, 3); -- Real Sociedad
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (48, 3); -- Villarreal
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (49, 3); -- Athletic Bilbao
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (50, 3); -- Celta Vigo
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (51, 3); -- Espanyol
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (52, 3); -- Getafe
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (53, 3); -- Mallorca
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (54, 3); -- Osasuna
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (55, 3); -- Rayo Vallecano
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (56, 3); -- Granada
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (57, 3); -- Alavés
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (58, 3); -- Cádiz
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (59, 3); -- Girona
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (60, 3); -- Almería

-- Inserir clubes da Serie A (COMPETITION_ID = 4)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (61, 4); -- Juventus
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (62, 4); -- AC Milan
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (63, 4); -- Inter Milan
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (64, 4); -- AS Roma
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (65, 4); -- Napoli
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (66, 4); -- Lazio
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (67, 4); -- Fiorentina
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (68, 4); -- Atalanta
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (69, 4); -- Torino
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (70, 4); -- Sassuolo
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (71, 4); -- Bologna
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (72, 4); -- Verona
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (73, 4); -- Sampdoria
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (74, 4); -- Lecce
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (75, 4); -- Genoa
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (76, 4); -- Monza
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (77, 4); -- Empoli
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (78, 4); -- Spezia
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (79, 4); -- Cagliari

-- Inserir clubes da Bundesliga (COMPETITION_ID = 5)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (80, 5); -- Bayern Munich
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (81, 5); -- Borussia Dortmund
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (82, 5); -- RB Leipzig
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (83, 5); -- Bayer Leverkusen
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (84, 5); -- Wolfsburg
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (85, 5); -- Eintracht Frankfurt
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (86, 5); -- Borussia Mönchengladbach
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (87, 5); -- Hoffenheim
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (88, 5); -- Mainz
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (89, 5); -- Freiburg
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (90, 5); -- Union Berlin
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (91, 5); -- Hertha Berlin
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (92, 5); -- Schalke 04
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (93, 5); -- Augsburg
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (94, 5); -- Stuttgart
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (95, 5); -- Cologne
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (96, 5); -- Werder Bremen
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (97, 5); -- Bochum

-- Inserir clubes da Ligue 1 (COMPETITION_ID = 6)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (98, 6); -- Paris Saint-Germain
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (99, 6); -- Olympique Marseille
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (100, 6); -- Lyon
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (101, 6); -- Monaco
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (102, 6); -- Lille
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (103, 6); -- Rennes
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (104, 6); -- Nice
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (105, 6); -- Nantes
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (106, 6); -- Strasbourg
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (107, 6); -- Montpellier
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (108, 6); -- Toulouse
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (109, 6); -- Brest
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (110, 6); -- Reims
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (111, 6); -- Lorient
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (112, 6); -- Clermont
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (113, 6); -- Lens
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (114, 6); -- Metz
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (115, 6); -- Angers
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (116, 6); -- Auxerre
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (117, 6); -- Troyes

-- Inserir clubes da Primeira Liga (COMPETITION_ID = 7)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (118, 7); -- Benfica
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (119, 7); -- Porto
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (120, 7); -- Sporting CP
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (121, 7); -- Braga
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (122, 7); -- Vitória de Guimarães
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (123, 7); -- Boavista
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (124, 7); -- Estoril
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (125, 7); -- Marítimo
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (126, 7); -- Gil Vicente
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (127, 7); -- Famalicão
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (128, 7); -- Casa Pia
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (129, 7); -- Arouca
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (130, 7); -- Rio Ave
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (131, 7); -- Chaves
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (132, 7); -- Paços de Ferreira

-- Inserir clubes da Champions League 2024/2025 (COMPETITION_ID = 8)
-- Premier League (Inglaterra)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (22, 8); -- Manchester City
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (24, 8); -- Arsenal
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (21, 8); -- Manchester United
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (32, 8); -- Newcastle United

-- La Liga (Espanha)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (42, 8); -- Barcelona
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (41, 8); -- Real Madrid
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (43, 8); -- Atlético de Madrid
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (47, 8); -- Real Sociedad

-- Serie A (Itália)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (65, 8); -- Napoli
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (63, 8); -- Inter de Milão
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (66, 8); -- Lazio
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (62, 8); -- Milan

-- Bundesliga (Alemanha)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (81, 8); -- Bayern de Munique
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (82, 8); -- Borussia Dortmund
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (83, 8); -- RB Leipzig
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (89, 8); -- Union Berlin

-- Ligue 1 (França)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (99, 8); -- Paris Saint-Germain (PSG)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (108, 8); -- Lens

-- Primeira Liga (Portugal)
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (119, 8); -- Benfica
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (120, 8); -- Porto
INSERT INTO TB_CLUB_COMPETITION (CLUB_ID, COMPETITION_ID) VALUES (122, 8); -- Braga