INSERT INTO TB_LEAGUE (NAME, CREATED_AT) VALUES ('Brasileirão', NOW());
INSERT INTO TB_LEAGUE (NAME, CREATED_AT) VALUES ('Premier League', NOW());
INSERT INTO TB_LEAGUE (NAME, CREATED_AT) VALUES ('La Liga', NOW());
INSERT INTO TB_LEAGUE (NAME, CREATED_AT) VALUES ('Serie A', NOW());
INSERT INTO TB_LEAGUE (NAME, CREATED_AT) VALUES ('Bundesliga', NOW());
INSERT INTO TB_LEAGUE (NAME, CREATED_AT) VALUES ('Ligue 1', NOW());
INSERT INTO TB_LEAGUE (NAME, CREATED_AT) VALUES ('Primeira Liga', NOW());